name: Generate Snake Animation ðŸ

on:
  schedule:
    - cron: "0 0 * * *"   # ExÃ©cute tous les jours Ã  minuit (UTC)
  workflow_dispatch:       # Permet de lancer manuellement
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for commits
        run: |
          git config --global user.name "Maimble Bot"
          git config --global user.email "ma.andriamparani@gmail.com"

      - name: Add fake commits for snake
        run: |
          echo "Update for snake $(date)" >> fake.txt
          for i in {1..5}; do
            echo "Extra line $i" >> fake.txt
            git add fake.txt
            git commit -m "Fake commit $i for snake $(date)" || echo "No changes to commit"
          done

      - name: Generate snake in dark and light mode
        uses: Platane/snk@v3
        with:
          github_user_name: mbomain
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
